export const ServiceProducts = [
    {
        id: 1,
        name: 'Consultaion For Divorce',
        href: '#',
        price: 7100.00,
        servicecategory: 'Marriage Astrology',
        inStock: false,
        leadTime: '7-8 business days',
        imageSrc: 'https://www.vinaybajrangi.com/upload/prod_pic/large/61.jpg',
        imageAlt: 'Consultaion For Delay In Marriage',
    },
    // {
    //     id: 2,
    //     name: 'Consultaion For Business Expansion',
    //     href: 'https://www.vinaybajrangi.com/services/consultation/business-expansion.php',
    //     price: 7100.00,
    //     servicecategory: 'Business Astrology',
    //     inStock: false,
    //     leadTime: '7-8 business days',
    //     imageSrc: 'https://www.vinaybajrangi.com/upload/prod_pic/large/92.jpg',
    //     imageAlt: 'Consultaion For Business Expansion',
    // },
    // {
    //     id: 3,
    //     name: 'Consultaion For Job Change Or Promotions',
    //     href: '#',
    //     price: 20000.00,
    //     servicecategory: 'Career Astrology',
    //     inStock: true,
    //     leadTime: '7-8 business days',
    //     imageSrc: 'https://www.vinaybajrangi.com/upload/prod_pic/large/101.jpg',
    //     imageAlt: 'Consultaion For Job Change Or Promotions',
    // },
    // {
    //     id: 4,
    //     name: 'Consultaion For Ancestral Property',
    //     href: '#',
    //     price: 7100.00,
    //     servicecategory: 'Property Astrology',
    //     inStock: true,
    //     leadTime: '7-8 business days',
    //     imageSrc: 'https://www.vinaybajrangi.com/upload/prod_pic/large/105.jpg',
    //     imageAlt: 'Consultaion For Ancestral Property',
    // },
];