// config/Horoscope.js
export const HoroscopeArticle = (year = "2024") => [
  {
    name: "Aries",
    url: `horoscope/aries-horoscope-${year}.php`,
    imgSrc: "https://www.vinaybajrangi.com/upload/rashi-img/Aries.png",
    link: `horoscope/aries-horoscope-${year}.php`,
    Hindiname: "मेष",
    hindiLink: `hindi/horoscope/mesh-varshik-rashifal-${year}.php`,
  },
  {
    name: "Taurus",
    url: `horoscope/taurus-horoscope-${year}.php`,
    imgSrc: "https://www.vinaybajrangi.com/upload/rashi-img/Tauras.png",
    link: `horoscope/taurus-horoscope-${year}.php`,
    Hindiname: "वृषभ",
    hindiLink: `hindi/horoscope/vrushabh-rashifal-${year}.php`,
  },
  {
    name: "Gemini",
    url: `horoscope/gemini-horoscope-${year}.php`,
    imgSrc: "https://www.vinaybajrangi.com/upload/rashi-img/Gemini.png",
    link: `horoscope/gemini-horoscope-${year}.php`,
    Hindiname: "मिथुन",
    hindiLink: `hindi/horoscope/mithun-rashifal-${year}.php`,
  },
  {
    name: "Cancer",
    url: `horoscope/cancer-horoscope-${year}.php`,
    imgSrc: "https://www.vinaybajrangi.com/upload/rashi-img/Cancer.png",
    link: `horoscope/cancer-horoscope-${year}.php`,
    Hindiname: "कर्क",
    hindiLink: `hindi/horoscope/kark-rashifal-${year}.php`,
  },
  {
    name: "Leo",
    url: `horoscope/leo-horoscope-${year}.php`,
    imgSrc: "https://www.vinaybajrangi.com/upload/rashi-img/Leo.png",
    link: `horoscope/leo-horoscope-${year}.php`,
    Hindiname: "सिंह",
    hindiLink: `hindi/horoscope/singh-rashifal-${year}.php`,
  },
  {
    name: "Virgo",
    url: `horoscope/virgo-horoscope-${year}.php`,
    imgSrc: "https://www.vinaybajrangi.com/upload/rashi-img/Virgo.png",
    link: `horoscope/virgo-horoscope-${year}.php`,
    Hindiname: "कन्या",
    hindiLink: `hindi/horoscope/kanya-rashifal-${year}.php`,
  },
  {
    name: "Libra",
    url: `horoscope/libra-horoscope-${year}.php`,
    imgSrc: "https://www.vinaybajrangi.com/upload/rashi-img/Libra.png",
    link: `horoscope/libra-horoscope-${year}.php`,
    Hindiname: "तुला",
    hindiLink: `hindi/horoscope/tula-rashifal-${year}.php`,
  },
  {
    name: "Scorpio",
    url: `horoscope/scorpio-horoscope-${year}.php`,
    imgSrc: "https://www.vinaybajrangi.com/upload/rashi-img/Scorpio.png",
    link: `horoscope/scorpio-horoscope-${year}.php`,
    Hindiname: "वृश्चिक",
    hindiLink: `https://www.vinaybajrangi.com/hindi/horoscope/vrshchik-rashifal-${year}.php`,
  },
  {
    name: "Sagittarius",
    url: `horoscope/sagittarius-horoscope-${year}.php`,
    imgSrc: "https://www.vinaybajrangi.com/upload/rashi-img/Sagittarius.png",
    link: `horoscope/sagittarius-horoscope-${year}.php`,
    Hindiname: "धनु",
    hindiLink: `hindi/horoscope/dhanu-rashifal-${year}.php`,
  },
  {
    name: "Capricorn",
    url: `horoscope/capricorn-horoscope-${year}.php`,
    imgSrc: "https://www.vinaybajrangi.com/upload/rashi-img/Capricorn.png",
    link: `horoscope/capricorn-horoscope-${year}.php`,
    Hindiname: "मकर",
    hindiLink: `hindi/horoscope/makar-rashifal-${year}.php`,
  },
  {
    name: "Aquarius",
    url: `horoscope/aquarius-horoscope-${year}.php`,
    imgSrc: "https://www.vinaybajrangi.com/upload/rashi-img/Aquarius.png",
    link: `horoscope/aquarius-horoscope-${year}.php`,
    Hindiname: "कुम्भ",
    hindiLink: `hindi/horoscope/kumbh-rashifal-${year}.php`,
  },
  {
    name: "Pisces",
    url: `horoscope/pisces-horoscope-${year}.php`,
    imgSrc: "https://www.vinaybajrangi.com/upload/rashi-img/pices.png",
    link: `horoscope/pisces-horoscope-${year}.php`,
    Hindiname: "मीन",
    hindiLink: `hindi/horoscope/meen-rashifal-${year}.php`,
  },
];
