import React from 'react';

export default function CancerPage() {
  return (
    <div className="max-w-6xl mx-auto shadow-2xl bg-white p-5 mt-5 mb-5 rounded-lg">
      <p className="text-sm mb-5 text-justify">The element of Cancer Zodiac Sign: Water</p>
      <p className="text-sm mb-5 text-justify">Ruling Planet of Cancer Zodiac Sign: Moon</p>
      <p className="text-sm mb-5 text-justify">Symbol of Cancer Zodiac Sign: The Crab</p>
      <p className="text-sm mb-5 text-justify">Cancer lucky colours are: Silvery, Grey</p>
      <p className="text-sm mb-5 text-justify">Cancer most compatible zodiac signs: Pisces and Scorpio</p>
      <h2 className="text-indigo-950 text-lg font-bold ">Cancer Characteristics, Personality & Traits</h2>
      <p className="text-sm mb-5 text-justify">For Cancerians, Cancer astrology today has emerged as an exhaustive and comprehensible guidance. With it, they can easily cope with their day-to-day life without succumbing to any pressure. <a href="https://www.vinaybajrangi.com/hindi/horoscope/daily-horoscope/kark.php" target="_blank"><span style={{ color: '#0000FF' }}><strong>Cancer daily horoscope</strong></span></a> is just a part of it that can help on daily basis. Cancer Zodiac Sign is like a hard coconut that is hard on the surface but soft in the inner core. Often the Cancer Personality is seen to take a hard way and suffer from aggressiveness. This aggression is mostly seen because of your self-defensive nature. You can make an exceptional parent as you seem to be sentimental and possess excellent calibre, which makes you memorize everything more efficiently. As a Cancer Zodiac Sign, you like to be a shield amongst your younger family members. As a Cancerian, you go through a lot of mood swings and are very sensual when it comes to love. Cancerian Personality is likely to make a good friend; you often seem to be very selective while choosing a friend. Although once you make friendship will remain firm and deep. You can be subtle at times, deep, and often be like the Moon; one can see in your behaviour as you are thrilled when you are receiving everything in fullest. Still, you lose your charm once you feel that you are getting it as per your expectation.</p>
      <p className="text-sm mb-5 text-justify">Your emotions are affected by anything, whether it is just a pin or a plane; however, being a Cancerian path in your life may not be easy because many factors influence you at every moment. As a Cancerian, you are very emotional and dependent upon your instincts and intuitions, which sometimes influence your decision, which you think is better for your own life. This is because Moon rules Cancerian. Cancer Zodiac Sign being ruled by Moon makes you bide the extremes of every situation, disturbing you most of the time. For more information, you can take a glance over Cancer astrology today. You will have to face extreme ups and downs as a Cancer Personality makes you a real example of keeping patience when it comes to living your life. You can sometimes confuse the person who knows you because of the sudden mood changes.</p>
      <p className="text-sm mb-5 text-justify">You have such an incredible abundance of thoughts to call upon as you are commonly profoundly inventive, typically sure, and you attempt to extend that you are in every case right. Anyway, indeed, you are definitely not. For the most part, you prefer to be peaceful and free and don&#39;t care to look for the help of yours. As a result of your violent nature of the Cancer Zodiac Sign, you invest a great deal of energy alone, and you are absolutely cheerful or totally pitiful. For all this, you should be grateful to Cancer astrology today that has shed light on your potential. Being a Cancerian, you regularly live inside the passionate world that rules you from inside. Settling on cautious choices can be your most significant challenge as your head and heart are continually in strife with one another.</p>
      <h2 className="text-indigo-950 text-lg font-bold ">Cancer Eminent Male and Female Personalities</h2>
      <p className="text-sm mb-5 text-justify">Cancer is indeed a gaudy zodiac sign and because of this many Cancer eminent personalities have shown outstanding performances to the world. The most popular Cancer personalities are Elon Musk, Tom Cruise, Sundar Pichai, Sylvester Stallone, Selena Gomez, Sourav Ganguly, Arjun Kapoor, Harbhajan Singh, Naseeruddin Shah, Priyanka Chopra, MS Dhoni, Katrina Kaif, Gautam Adani, Kalpana Chawla and Sunil Gavaskar. They have created milestones in history.</p>
      <h2 className="text-indigo-950 text-lg font-bold ">Different Facets of Cancer Horoscope</h2>
      <p className="text-sm mb-5 text-justify">Cancer horoscope is a vast subject and includes many facets which prove to be very useful for people:</p>
      <p className="text-sm mb-5 text-justify"><strong>Cancer Horoscope Tomorrow</strong>: Tomorrow is uncertain and none knows what may turn up next. For Cancerians, Cancer horoscope tomorrow is very useful. By reading it, they can remain ready to face any eventuality and do many other things.</p>
      <p className="text-sm mb-5 text-justify"><strong>Cancer Love Horoscope Today</strong>: Love is a very exciting thing and people remain impatient to know about their compatibility with their life partner. Through Cancer love horoscope today, they can know whether their love life will be fruitful or not.</p>
      <p className="text-sm mb-5 text-justify"><strong>Cancer Career Horoscope Today:</strong> In terms of career, youngsters remain curious to know about their future. Because of their indecisive nature, they can take guidance from Cancer Career Horoscope Today. It will let them know what career suits them the best.</p>
      <p className="text-sm mb-5 text-justify"><strong>Cancer Health Horoscope Today</strong>: Health is something about which people think seriously. They eagerly wait for the delivery of newspaper at the threshold of their doors to know their health predictions. Cancer health horoscope today let them know what they should and what they should not do to maintain their fitness.</p>
      <p className="text-sm mb-5 text-justify"><strong>Cancer Weekly Horoscope</strong>: With <a href="https://www.vinaybajrangi.com/horoscope/weekly-horoscope/cancer.php" target="_blank"><span><strong>Cancer weekly horoscope</strong></span></a>, they can know many things about their working methodologies, plans, etc. It will also let them know whether time is favourable to take a venture or not. As a result, they will be saved from mismanagement and unnecessary hassles.</p>
      <p className="text-sm mb-5 text-justify"><strong>Cancer Monthly Horoscope</strong>: For a broader preview of astrology, <a href="https://www.vinaybajrangi.com/horoscope/monthly-horoscope/cancer.php" target="_blank"><span><strong>Cancer monthly horoscope</strong></span></a> proves to be more useful for Cancerians. It provides them complete details regarding their work, finance, recreation, etc. for their whole month.</p>
      <h2 className="text-indigo-950 text-lg font-bold ">Cancer Zodiac Signs Strengths</h2>
      <p className="text-sm mb-5 text-justify">As you have known about the characteristics of Cancer Zodiac Sign, let&#39;s find out how these can be a beneficial trait of your personality.</p>
      <ol className='list-decimal mb-5 text-sm'>
        <li className="mb-5">As a Cancerian, you are confident, and you are very careful when it comes to your self-esteemed disposition.</li>
        <li className="mb-5">Cancer Personality is very creative, so you share an uncommon expression and thoughts.</li>
        <li className="mb-5">You are immensely charming, and sometimes you appear to be spellbinding when it comes to representing yourself. This makes you everyone&#39;s favorite.</li>
        <li className="mb-5">You are emotional and always have lofty feelings for everyone. Your sensitive nature makes you open to new thoughts, but at the same time, you are very sentimental and sympathetic.</li>
        <li className="mb-5">As a Cancer Personality, you are intuitive, which is based on your active conscience and are very moody, which makes you unpredictable at times.</li>
        <li className="mb-5">You being a Cancerian, your patience make you hardworking; your protective nature makes you fight with the inner strength. You can also know more your traits through Cancer <a href="https://www.vinaybajrangi.com/horoscope/daily-horoscope.php" target="_blank"><span>Moon sign horoscope today</span></a>, which can equip with lots of information regarding four physical trait.</li>
      </ol>
      <h2 className="text-indigo-950 text-lg font-bold ">Cancer Zodiac Sign Weakness and Shortcomings</h2>
      <p className="text-sm mb-5 text-justify">Redundancy of every trait can lead to harm. Cancer Personality; in the points below, you will feel the shortcomings of your characteristics, where you have to keep control of your traits.</p>
      <ol className='list-decimal mb-5 text-sm'>
        <li className="mb-5">Cancer Zodiac Sign, your confidence can make you awfully inspiring, making your surroundings a bit disrespectful.</li>
        <li className="mb-5">You have many creative ideas at a time, and your charm may be another person&#39;s insecurity; your emotional factor can make you face many ups and downs in mood.</li>
        <li className="mb-5">Your imaginative approach makes you overreact highly irrational at times.</li>
        <li className="mb-5">Your moody nature makes it challenging to deal with Cancerian; your extremist nature in patience can sometimes make you dull and doleful.</li>
        <li className="mb-5">Cancer Zodiac Sign makes you highly protective, and this makes you a scary person as you hate failing, and this can turn in the wrong direction. Your sensitive nature can confuse your views.</li>
      </ol>
      <h2 className="text-indigo-950 text-lg font-bold ">Cancer Lucky Number and Colour</h2>
      <p className="text-sm mb-5 text-justify">By acquiring Cancer lucky number, Cancerians can do many things successfully, such as passing exams confidently with lucky roll numbers, buying groceries, dresses, etc. with lucky voucher numbers, etc. Similarly, with Cancer lucky colour, Cancerians can cast indelible impression on others and create a niche for themselves.</p>
      <h2 className="text-indigo-950 text-lg font-bold ">Facts about Cancer Woman</h2>
      <p className="text-sm mb-5 text-justify">Apart from men, women too can be benefitted from Cancer daily horoscope. A Cancer Zodiac Sign lady wears one of the most ladylike indications of the world. It is your most novel force. Subsequently, you can likewise be intricate, complicated, and manipulative. You additionally realize how to cause you to feel you and acknowledged. You earnest humility and is equally intense. Simultaneously you are viewed as an extraordinary temptress. You can make men give up their riches and heart to yours. At the point when your bombs in adoration, your sense of self goes wild. Truth be told, love and sex frequently don&#39;t go to get your for a Cancer Zodiac Sign Woman. Like your states of mind, you are now and again confounded and can be pulled in indeed to somebody with whom you aren&#39;t enamoured. In any case, you can go gaga for a person with whom you wouldn&#39;t like to make love always.</p>
      <p className="text-sm mb-5 text-justify">A Cancer Zodiac Sign Woman adores positions and can acknowledge an assortment of obligations. You can work very well in a casual domain. You can make an extraordinary author, artist, on-screen character, painter, educator, or whatever else that offers you&#39;re a chance to support your confidence. You can be an incredible instructor. You can likewise well with the design items. In the event that you accept that you can earn substantial sums of money throughout everyday life, you will, without a doubt, do as such. You likewise remember that it is essential to be ready for troublesome occasions. It is true that you are inclined towards a luxurious life. But then you also are very sensible about going through cash.</p>
      <h2 className="text-indigo-950 text-lg font-bold ">Cancer Zodiac Sign Career and Money</h2>
      <p className="text-sm mb-5 text-justify">At the point when a vocation needs to finish, being a Cancer Zodiac Sign, you will roll your sleeves up and finish it effectively. On the off chance that you are disregarded to work, you, for the most part, perform better than when encircled by others, faithful to your boss, and concentrated on the assignment. You will have incredible professions as medical caretakers, servants, cultivators, politicians, and decorators. For more, have a peep into Cancer horoscope today. Through it, you will be able to gather much more information regarding your personality.</p>
      <p className="text-sm mb-5 text-justify">For Cancer Zodiac, Sign agents, security, and money are of incredible significance and represent the excellent explanation they fill in as much as you do. You effectively acquire cash and aren&#39;t accustomed to spending it across the board day. It is your objective to spare, contribute, and watch your speculations develop day by day. You can also take some tips from Cancer daily horoscope to fulfil your objective. Creative and high at overseeing time and funds, this is an indication that is regularly responsible for all money in the family, keeping their accomplice or other relatives levelled out.</p>
      <h2 className="text-indigo-950 text-lg font-bold ">Cancer Relationship with Friends and Family</h2>
      <p className="text-sm mb-5 text-justify">With regards to friendship, Cancer Zodiac Sign natives will readily associate with new social contacts; however, you are very delicate of individuals not endorsed by their nearest encompassing. You can also take a glance over Cancer horoscope today to know about your compatibility with your loved ones. Loaded up with deference for individuals you impart to effectively, you see all contacts through their enthusiastic crystal instead of sincere interest or status. Above all else, you appreciate associating at home, where close air can be made, and profound understanding partook in conditions under your influence. Natural and sympathetic, you are now and then challenging to comprehend from a very sophisticated perspective.</p>
      <p className="text-sm mb-5 text-justify">Cancer Zodiac Sign is the indication of family, and you people care about family bonds and your home more than some other evidence of the zodiac. Cancer daily horoscope helps Cancerians a lot in maintaining a good relationship with family members. Profoundly melancholy, you will, in general, tenaciously protect family recollections, keeping them flawless for a considerable length of time. At the point when your own lives are satisfied, you make great, caring guardians that appear to know how your youngsters feel in any event when they are miles separated.</p>
      <h2 className="text-indigo-950 text-lg font-bold ">Cancer Zodiac Sign Compatibility</h2>
      <p className="text-sm mb-5 text-justify">Cancer compatibility is predicted with the following zodiac signs:</p>
      <p className="text-sm mb-5 text-justify"><strong>Taurus:</strong> Taurus and Cancer Zodiac Sign are indistinguishable in that they share a typical requirement for security and a feeling of lasting quality with regards to every single significant part of their lives. Their disparities are really helpful, everyone&#39;s individual conditions compensating for deferent&#39;s shortcomings. The two signs are delicate and mindful to their friends and family, making for a crystal gazing love coordinate that is probably going to stand the trial of time very well. You can also get some ideas from Cancer horoscope today about your compatibility with this zodiac sign.</p>
      <p className="text-sm mb-5 text-justify"><strong>Scorpio:</strong> Scorpio can be a prickly love coordinate for some zodiac locals, yet this isn&#39;t the situation with Cancer. Cancer Personality shares common possessive inclinations assisted Scorpio with having a sense of safety and needed in the relationship. At the same time, Scorpio&#39;s energy supports timid, withdrawn Cancer Zodiac Sign to become friendlier more frequently. Every one&#39;s intrinsic character causes the other to feel sheltered and cherished, making this an agreeable love coordinate.</p>
      <p className="text-sm mb-5 text-justify"><strong>Virgo:</strong> Probably, the best thing about a Virgo-Cancer blending is the huge limit concerning caring that is there. Both Virgo and Cancer Zodiac Sign are signs that have a great time caring for their friends and family, and their association will be a caring one, in fact. Cancer daily horoscope also sheds light on you how you will be compatible with this zodiac sign. They are likewise incredible at speaking with one another, despite the way that Virgo consistently talks from a down to earth viewpoint, while Cancer is progressively emotive.</p>
      <h2 className="text-indigo-950 text-lg font-bold ">Cancer Worst Matches</h2>
      <p className="text-sm mb-5 text-justify">The zodiac signs with which Cancerians will be incompatible include the following:</p>
      <p className="text-sm mb-5 text-justify"><strong>Aquarius:</strong> Aquarian locals love fun and assortment, which tends to conflict with Cancer&#39;s Zodiac Sign requirement for harmony, security, and asylum. Cancer Personality growth&#39;s customary; conservative methodology toward life doesn&#39;t blend in with Aquarius&#39; unpredictable, regularly supercilious method. Aquarians are likewise frequently far and away excessively sincerely separated to meet Cancer Zodiac Sign&#39;s essential needs. At the same time, Cancer&#39;s testiness pesters and exasperates Aquarius. For more, have a look at Cancer horoscope today. It will equip you with lots of information.</p>
      <p className="text-sm mb-5 text-justify"><strong>Libra:</strong> In spite of the fact that this matching has the limit concerning success, it is impossible, because of the wildly various ways these two people work. Cancer Zodiac Sign is all feeling and feeling. At the same time, Libra approaches life on increasingly savvy terms, making both of them communicate in totally various dialects. Libra&#39;s social ways can conflict with Cancer Personality increasingly independent inclinations. At the same time, Cancer Zodiac Sign touchiness can demonstrate frightening for Libras who want to keep away from dramatization at whatever point conceivable. You can also take some help from Cancer daily horoscope that will guide in the right direction.</p>
      <p className="text-sm mb-5 text-justify"><strong>Gemini:</strong> Despite the fact that it is workable for Cancer Zodiac Sign and Gemini to interface well on an enthusiastic level, these two are at last extremely extraordinary to truly make for a fruitful association. Cancer Personality growth is independent and close to a loner like a great deal of the time. At the same time, Gemini is unquenchably social, liking to be around others as a general rule. Malignant growths likewise favour security and harmony, while Gemini is about assortment and eccentrics. Eventually, the Gemini could very well get eager and start searching for greener fields troublesome if not difficult to accomplish.</p>
      <p className="text-sm mb-5 text-justify">You can read more about Cancer on <a href="https://www.vinaybajrangi.com/zodiac-signs-compatibility/cancer-with-other-signs.php" target="_blank">Cancer compatibility</a>, <a href="https://www.vinaybajrangi.com/services/online-report/know-your-marriage-timing.php">Know, the Timing of your Marriage</a>, and <a href="https://www.vinaybajrangi.com/planets.php" target="_blank">effects of planets in different houses & signs</a>?</p>
    </div>
  );
}
