<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<html>
<head>
<title>Index of /upload/planetarysubimage</title>
</head>
<body>
<h1>Index of /upload/planetarysubimage</h1>
<table>
<tr><th valign="top"><img src="../../icons/blank.gif" alt="[ICO]"></th><th><a href="index-1.htm?C=N;O=D">Name</a></th><th><a href="index-2.htm?C=M;O=A">Last modified</a></th><th><a href="index-3.htm?C=S;O=A">Size</a></th><th><a href="index-4.htm?C=D;O=A">Description</a></th></tr>
<tr><th colspan="5"><hr></th></tr>
<tr><td valign="top"><img src="../../icons/back.gif" alt="[PARENTDIR]"></td><td><a href="../index.htm">Parent Directory</a></td><td>&nbsp;</td><td align="right"> - </td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/image2.gif" alt="[IMG]"></td><td><a href="1_planetary_mercury.jpg">1_planetary_mercury.jpg</a></td><td align="right">2020-11-16 15:58 </td><td align="right">4.9K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="2_2_Mars%20in%20aquarius.webp">2_2_Mars in aquarius.webp</a></td><td align="right">2021-08-28 18:16 </td><td align="right"> 15K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/image2.gif" alt="[IMG]"></td><td><a href="2_Mars-Transit1.jpg">2_Mars-Transit1.jpg</a></td><td align="right">2020-11-24 16:32 </td><td align="right"> 27K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="2_Mars%20in%20aquarius.webp">2_Mars in Aquarius.webp</a></td><td align="right">2020-11-19 16:29 </td><td align="right"> 24K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="2_Mars%20in%20aquarius.webp">2_Mars in aquarius.webp</a></td><td align="right">2020-12-14 18:22 </td><td align="right"> 15K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="2_The-12-Zodiac-Signs-of-Vedic-Astrology-1.webp">2_The-12-Zodiac-Signs-of-Vedic-Astrology-1.webp</a></td><td align="right">2020-11-19 16:39 </td><td align="right"> 91K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="2_detail_2_detail_mars%20transit%20in%20aquarius.webp">2_detail_2_detail_mars transit in aquarius.webp</a></td><td align="right">2021-08-28 18:16 </td><td align="right"> 30K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/image2.gif" alt="[IMG]"></td><td><a href="2_detail_Mars-Transit.jpg">2_detail_Mars-Transit.jpg</a></td><td align="right">2020-11-24 16:32 </td><td align="right"> 60K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="2_detail_mars%20transit%20in%20aquarius.webp">2_detail_mars transit in aquarius.webp</a></td><td align="right">2020-12-14 18:22 </td><td align="right"> 30K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="3_3_Mars%20in%20aries.webp">3_3_Mars in aries.webp</a></td><td align="right">2021-07-26 09:08 </td><td align="right"> 13K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="3_Mars%20in%20aries.webp">3_Mars in aries.webp</a></td><td align="right">2020-12-14 18:08 </td><td align="right"> 13K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="3_detail_3_detail_mars%20transit%20in%20aries.webp">3_detail_3_detail_mars transit in aries.webp</a></td><td align="right">2021-07-26 09:08 </td><td align="right"> 36K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="3_detail_mars%20transit%20in%20aries.webp">3_detail_mars transit in aries.webp</a></td><td align="right">2020-12-14 18:08 </td><td align="right"> 36K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="4_detail_sun%20transit%20in%20aquarius.webp">4_detail_sun transit in aquarius.webp</a></td><td align="right">2021-09-09 13:25 </td><td align="right"> 32K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="4_sun%20in%20aquarius.webp">4_sun in aquarius.webp</a></td><td align="right">2021-09-09 13:25 </td><td align="right"> 13K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="5_detail_sun%20transit%20in%20cancer.webp">5_detail_sun transit in cancer.webp</a></td><td align="right">2021-09-09 13:25 </td><td align="right"> 31K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="5_sun%20in%20cancer.webp">5_sun in cancer.webp</a></td><td align="right">2021-09-09 13:25 </td><td align="right"> 13K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="6_detail_sun%20transit%20in%20capricorn.webp">6_detail_sun transit in capricorn.webp</a></td><td align="right">2021-09-09 13:26 </td><td align="right"> 32K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="6_sun%20in%20capricorn.webp">6_sun in capricorn.webp</a></td><td align="right">2021-09-09 13:26 </td><td align="right"> 13K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="7_detail_sun%20transit%20in%20gemini.webp">7_detail_sun transit in gemini.webp</a></td><td align="right">2021-09-09 13:32 </td><td align="right"> 30K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="7_sun%20in%20gemini.webp">7_sun in gemini.webp</a></td><td align="right">2021-09-09 13:32 </td><td align="right"> 10K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="8_8_Mars%20in%20cancer.webp">8_8_Mars in cancer.webp</a></td><td align="right">2021-07-26 11:29 </td><td align="right"> 15K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="8_Mars%20in%20cancer.webp">8_Mars in cancer.webp</a></td><td align="right">2020-12-19 16:24 </td><td align="right"> 15K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="8_detail_8_detail_mars%20transit%20in%20cancer.webp">8_detail_8_detail_mars transit in cancer.webp</a></td><td align="right">2021-07-26 11:29 </td><td align="right"> 31K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="8_detail_mars%20transit%20in%20cancer.webp">8_detail_mars transit in cancer.webp</a></td><td align="right">2020-12-19 16:24 </td><td align="right"> 31K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="9_9_Mars%20in%20Capricorn.webp">9_9_Mars in Capricorn.webp</a></td><td align="right">2021-08-27 17:44 </td><td align="right"> 15K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="9_Mars%20in%20Capricorn.webp">9_Mars in Capricorn.webp</a></td><td align="right">2020-12-14 18:22 </td><td align="right"> 15K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="9_detail_9_detail_mars%20transit%20in%20Capricorn.webp">9_detail_9_detail_mars transit in Capricorn.webp</a></td><td align="right">2021-08-27 17:44 </td><td align="right"> 30K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="9_detail_mars%20transit%20in%20Capricorn.webp">9_detail_mars transit in Capricorn.webp</a></td><td align="right">2020-12-14 18:22 </td><td align="right"> 30K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="10_10_Mars%20in%20gemini.webp">10_10_Mars in gemini.webp</a></td><td align="right">2021-07-26 10:43 </td><td align="right"> 14K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="10_Mars%20in%20gemini.webp">10_Mars in gemini.webp</a></td><td align="right">2020-12-19 16:24 </td><td align="right"> 14K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="10_detail_10_detail_mars%20transit%20in%20gemini.webp">10_detail_10_detail_mars transit in gemini.webp</a></td><td align="right">2021-07-26 10:43 </td><td align="right"> 31K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="10_detail_mars%20transit%20in%20gemini.webp">10_detail_mars transit in gemini.webp</a></td><td align="right">2020-12-19 16:24 </td><td align="right"> 31K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="11_11_Mars%20in%20leo.webp">11_11_Mars in leo.webp</a></td><td align="right">2021-09-07 16:49 </td><td align="right"> 14K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="11_Mars%20in%20leo.webp">11_Mars in leo.webp</a></td><td align="right">2020-12-19 16:25 </td><td align="right"> 14K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="11_detail_11_detail_mars%20transit%20in%20leo.webp">11_detail_11_detail_mars transit in leo.webp</a></td><td align="right">2021-09-07 16:49 </td><td align="right"> 30K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="11_detail_mars%20transit%20in%20leo.webp">11_detail_mars transit in leo.webp</a></td><td align="right">2020-12-19 16:25 </td><td align="right"> 30K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="12_12_venus%20in%20aries.webp">12_12_venus in aries.webp</a></td><td align="right">2021-11-14 23:55 </td><td align="right"> 14K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/image2.gif" alt="[IMG]"></td><td><a href="12_detail_venus%20transit%20in%20aries%20%281%29.jpg">12_detail_venus transit in aries (1).jpg</a></td><td align="right">2021-11-06 16:20 </td><td align="right"> 21K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="12_detail_venus%20transit%20in%20aries.webp">12_detail_venus transit in aries.webp</a></td><td align="right">2020-12-16 16:49 </td><td align="right"> 33K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="12_venus%20in%20aries.webp">12_venus in aries.webp</a></td><td align="right">2020-12-16 16:49 </td><td align="right"> 14K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="13_13_venus%20in%20taurus.webp">13_13_venus in taurus.webp</a></td><td align="right">2021-11-14 23:55 </td><td align="right"> 15K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/image2.gif" alt="[IMG]"></td><td><a href="13_detail_venus%20transit%20in%20taurus.jpg">13_detail_venus transit in taurus.jpg</a></td><td align="right">2021-11-13 17:04 </td><td align="right"> 21K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="13_detail_venus%20transit%20in%20taurus.webp">13_detail_venus transit in taurus.webp</a></td><td align="right">2020-12-16 17:18 </td><td align="right"> 33K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="13_venus%20in%20taurus.webp">13_venus in taurus.webp</a></td><td align="right">2020-12-16 17:18 </td><td align="right"> 15K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="14_detail_venus%20transit%20in%20gemini.webp">14_detail_venus transit in gemini.webp</a></td><td align="right">2022-07-13 12:11 </td><td align="right"> 34K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="14_venus%20in%20gemini.webp">14_venus in gemini.webp</a></td><td align="right">2022-07-13 12:11 </td><td align="right"> 15K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="15_15_venus%20in%20cancer.webp">15_15_venus in cancer.webp</a></td><td align="right">2022-04-08 12:27 </td><td align="right"> 15K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="15_detail_15_detail_venus%20transit%20in%20cancer.webp">15_detail_15_detail_venus transit in cancer.webp</a></td><td align="right">2022-04-08 12:27 </td><td align="right"> 34K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="15_detail_venus%20transit%20in%20cancer.webp">15_detail_venus transit in cancer.webp</a></td><td align="right">2020-12-16 17:15 </td><td align="right"> 34K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="15_venus%20in%20cancer.webp">15_venus in cancer.webp</a></td><td align="right">2020-12-16 17:15 </td><td align="right"> 15K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="16_16_venus%20in%20leo.webp">16_16_venus in leo.webp</a></td><td align="right">2022-04-08 13:46 </td><td align="right"> 14K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="16_detail_16_detail_venus%20transit%20in%20leo.webp">16_detail_16_detail_venus transit in leo.webp</a></td><td align="right">2022-04-08 13:46 </td><td align="right"> 33K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="16_detail_venus%20transit%20in%20leo.webp">16_detail_venus transit in leo.webp</a></td><td align="right">2020-12-16 17:16 </td><td align="right"> 33K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="16_venus%20in%20leo.webp">16_venus in leo.webp</a></td><td align="right">2020-12-16 17:16 </td><td align="right"> 14K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="17_detail_17_detail_venus%20transit%20in%20virgo.webp">17_detail_17_detail_venus transit in virgo.webp</a></td><td align="right">2022-09-21 18:09 </td><td align="right"> 34K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="17_detail_venus%20transit%20in%20virgo.webp">17_detail_venus transit in virgo.webp</a></td><td align="right">2020-12-16 17:14 </td><td align="right"> 34K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="17_venus%20in%20virgo.webp">17_venus in virgo.webp</a></td><td align="right">2020-12-16 17:14 </td><td align="right"> 15K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="18_detail_venus%20transit%20in%20libra.webp">18_detail_venus transit in libra.webp</a></td><td align="right">2020-12-16 16:49 </td><td align="right"> 33K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="18_venus%20in%20libra.webp">18_venus in libra.webp</a></td><td align="right">2020-12-16 16:49 </td><td align="right"> 14K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="19_19_venus%20in%20scorpio.webp">19_19_venus in scorpio.webp</a></td><td align="right">2022-11-05 18:30 </td><td align="right"> 15K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="19_detail_%E0%A4%B6%E0%A5%81%E0%A4%95%E0%A5%8D%E0%A4%B0%20%E0%A4%97%E0%A5%8B%E0%A4%9A%E0%A4%B0.webp">19_detail_शुक्र गोचर.webp</a></td><td align="right">2022-11-05 18:30 </td><td align="right"> 26K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="19_detail_venus%20transit%20in%20scorpio.webp">19_detail_venus transit in scorpio.webp</a></td><td align="right">2020-12-10 13:43 </td><td align="right"> 26K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="19_venus%20in%20scorpio.webp">19_venus in scorpio.webp</a></td><td align="right">2020-12-10 13:48 </td><td align="right"> 15K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="20_20_venus%20in%20Sagittarius.webp">20_20_venus in Sagittarius.webp</a></td><td align="right">2021-10-22 13:59 </td><td align="right"> 15K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="20_detail_20_detail_venus%20transit%20in%20Sagittarius.webp">20_detail_20_detail_venus transit in Sagittarius.webp</a></td><td align="right">2021-10-22 13:59 </td><td align="right"> 33K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="20_detail_venus%20transit%20in%20Sagittarius.webp">20_detail_venus transit in Sagittarius.webp</a></td><td align="right">2020-12-16 17:28 </td><td align="right"> 33K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="20_venus%20in%20Sagittarius.webp">20_venus in Sagittarius.webp</a></td><td align="right">2020-12-16 17:28 </td><td align="right"> 15K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="21_21_venus%20in%20capricorn.webp">21_21_venus in capricorn.webp</a></td><td align="right">2021-10-25 16:44 </td><td align="right"> 15K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="21_detail_21_detail_venus%20transit%20in%20capricorn.webp">21_detail_21_detail_venus transit in capricorn.webp</a></td><td align="right">2021-10-25 16:44 </td><td align="right"> 34K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="21_detail_venus%20transit%20in%20capricorn.webp">21_detail_venus transit in capricorn.webp</a></td><td align="right">2020-12-16 17:30 </td><td align="right"> 34K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="21_venus%20in%20capricorn.webp">21_venus in capricorn.webp</a></td><td align="right">2020-12-16 17:30 </td><td align="right"> 15K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="22_22_venus%20in%20aquarius.webp">22_22_venus in aquarius.webp</a></td><td align="right">2021-10-27 15:01 </td><td align="right"> 16K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="22_detail_22_detail_venus%20transit%20in%20aquarius.webp">22_detail_22_detail_venus transit in aquarius.webp</a></td><td align="right">2021-10-27 15:01 </td><td align="right"> 34K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="22_detail_venus%20transit%20in%20aquarius.webp">22_detail_venus transit in aquarius.webp</a></td><td align="right">2020-12-16 16:56 </td><td align="right"> 34K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="22_venus%20in%20aquarius.webp">22_venus in aquarius.webp</a></td><td align="right">2020-12-16 16:51 </td><td align="right"> 16K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="23_23_venus%20in%20pisces.webp">23_23_venus in pisces.webp</a></td><td align="right">2021-11-01 18:04 </td><td align="right"> 16K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/image2.gif" alt="[IMG]"></td><td><a href="23_detail_22_detail_venus%20transit%20in%20aquarius.png">23_detail_22_detail_venus transit in aquarius.png</a></td><td align="right">2021-11-01 18:08 </td><td align="right">154K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/text.gif" alt="[TXT]"></td><td><a href="23_detail_Venus%20Transit%20in%20Pisces.html.htm">23_detail_Venus Transit in Pisces.html</a></td><td align="right">2021-11-01 18:04 </td><td align="right">293K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="23_detail_venus%20transit%20in%20pisces.webp">23_detail_venus transit in pisces.webp</a></td><td align="right">2020-12-16 16:54 </td><td align="right"> 34K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="23_venus%20in%20pisces.webp">23_venus in pisces.webp</a></td><td align="right">2020-12-16 16:54 </td><td align="right"> 16K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="24_detail_Jupiter%20transit%20in%20capricorn.webp">24_detail_Jupiter transit in capricorn.webp</a></td><td align="right">2022-07-20 16:36 </td><td align="right"> 32K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="24_jupiter-in-capricorn.webp">24_jupiter-in-capricorn.webp</a></td><td align="right">2020-11-20 12:18 </td><td align="right"> 29K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="24_jupiter%20in%20capricorn.webp">24_jupiter in capricorn.webp</a></td><td align="right">2022-07-20 16:36 </td><td align="right"> 15K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="25_detail_sun%20transit%20in%20aries.webp">25_detail_sun transit in aries.webp</a></td><td align="right">2021-09-09 13:34 </td><td align="right"> 31K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="25_sun%20in%20aries.webp">25_sun in aries.webp</a></td><td align="right">2021-09-09 13:34 </td><td align="right"> 12K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="26_detail_sun%20transit%20in%20leo.webp">26_detail_sun transit in leo.webp</a></td><td align="right">2021-09-09 13:34 </td><td align="right"> 28K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="26_sun%20in%20leo.webp">26_sun in leo.webp</a></td><td align="right">2021-09-09 13:34 </td><td align="right"> 12K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="27_detail_sun%20transit%20in%20libra.webp">27_detail_sun transit in libra.webp</a></td><td align="right">2021-09-09 13:35 </td><td align="right"> 29K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="27_sun%20in%20libra.webp">27_sun in libra.webp</a></td><td align="right">2021-09-09 13:35 </td><td align="right"> 13K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="28_detail_sun%20transit%20in%20sagittarius.webp">28_detail_sun transit in sagittarius.webp</a></td><td align="right">2021-09-09 13:36 </td><td align="right"> 30K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="28_sun%20in%20sagattirus.webp">28_sun in sagattirus.webp</a></td><td align="right">2021-09-09 13:36 </td><td align="right"> 11K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="29_detail_sun%20transit%20in%20pisces.webp">29_detail_sun transit in pisces.webp</a></td><td align="right">2021-09-09 13:37 </td><td align="right"> 32K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="29_sun%20in%20pisces.webp">29_sun in pisces.webp</a></td><td align="right">2021-09-09 13:37 </td><td align="right"> 13K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="30_detail_sun%20transit%20in%20scorpio.webp">30_detail_sun transit in scorpio.webp</a></td><td align="right">2021-09-09 13:37 </td><td align="right"> 32K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="30_sun%20in%20scorpio.webp">30_sun in scorpio.webp</a></td><td align="right">2021-09-09 13:37 </td><td align="right"> 11K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="30_sun%20scorpio.webp">30_sun scorpio.webp</a></td><td align="right">2020-11-27 13:31 </td><td align="right"> 14K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="31_31_sun%20in%20taurus.webp">31_31_sun in taurus.webp</a></td><td align="right">2021-08-12 16:48 </td><td align="right"> 12K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="31_detail_31_detail_sun%20transit%20in%20taurus.webp">31_detail_31_detail_sun transit in taurus.webp</a></td><td align="right">2021-08-12 16:48 </td><td align="right"> 29K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="31_detail_sun%20transit%20in%20taurus.webp">31_detail_sun transit in taurus.webp</a></td><td align="right">2020-12-02 13:26 </td><td align="right"> 29K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="31_sun%20in%20taurus.webp">31_sun in taurus.webp</a></td><td align="right">2020-12-02 13:26 </td><td align="right"> 12K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="32_32_sun%20in%20virgo.webp">32_32_sun in virgo.webp</a></td><td align="right">2021-08-31 17:25 </td><td align="right"> 13K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="32_detail_32_detail_sun%20transit%20in%20virgo.webp">32_detail_32_detail_sun transit in virgo.webp</a></td><td align="right">2021-08-31 17:25 </td><td align="right"> 30K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="32_detail_sun%20transit%20in%20virgo.webp">32_detail_sun transit in virgo.webp</a></td><td align="right">2020-12-02 12:59 </td><td align="right"> 30K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="32_sun%20in%20virgo.webp">32_sun in virgo.webp</a></td><td align="right">2020-12-02 12:59 </td><td align="right"> 13K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="33_33_Mercury%20in%20Aquarius.webp">33_33_Mercury in Aquarius.webp</a></td><td align="right">2021-10-09 17:39 </td><td align="right"> 13K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="33_Mercury%20in%20Aquarius.webp">33_Mercury in Aquarius.webp</a></td><td align="right">2020-12-16 16:16 </td><td align="right"> 13K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="33_detail_33_detail_mercury%20transit%20in%20Aquarius.webp">33_detail_33_detail_mercury transit in Aquarius.webp</a></td><td align="right">2021-10-09 17:39 </td><td align="right"> 32K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="33_detail_mercury%20transit%20in%20Aquarius.webp">33_detail_mercury transit in Aquarius.webp</a></td><td align="right">2020-12-16 16:16 </td><td align="right"> 32K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="34_34_Mercury%20in%20gemini.webp">34_34_Mercury in gemini.webp</a></td><td align="right">2021-09-15 15:34 </td><td align="right"> 15K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="34_Mercury%20in%20gemini.webp">34_Mercury in gemini.webp</a></td><td align="right">2020-12-15 18:17 </td><td align="right"> 15K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="34_detail_34_detail_mercury%20transit%20in%20gemini.webp">34_detail_34_detail_mercury transit in gemini.webp</a></td><td align="right">2021-09-15 15:34 </td><td align="right"> 32K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="34_detail_mercury%20transit%20in%20gemini.webp">34_detail_mercury transit in gemini.webp</a></td><td align="right">2020-12-15 18:17 </td><td align="right"> 32K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="35_35_Mercury%20in%20cancer.webp">35_35_Mercury in cancer.webp</a></td><td align="right">2021-09-15 16:12 </td><td align="right"> 16K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="35_Mercury%20in%20cancer.webp">35_Mercury in cancer.webp</a></td><td align="right">2020-12-15 17:53 </td><td align="right"> 16K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="35_detail_35_detail_mercury%20transit%20in%20cancer.webp">35_detail_35_detail_mercury transit in cancer.webp</a></td><td align="right">2021-09-15 16:12 </td><td align="right"> 32K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="35_detail_mercury%20transit%20in%20cancer.webp">35_detail_mercury transit in cancer.webp</a></td><td align="right">2020-12-15 17:53 </td><td align="right"> 32K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="36_36_Mercury%20in%20capricorn.webp">36_36_Mercury in capricorn.webp</a></td><td align="right">2021-10-02 14:56 </td><td align="right"> 15K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="36_Mercury%20in%20capricorn.webp">36_Mercury in capricorn.webp</a></td><td align="right">2020-12-16 16:18 </td><td align="right"> 15K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="36_detail_36_detail_mercury%20transit%20in%20capricorn.webp">36_detail_36_detail_mercury transit in capricorn.webp</a></td><td align="right">2021-10-02 14:56 </td><td align="right"> 30K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="36_detail_mercury%20transit%20in%20capricorn.webp">36_detail_mercury transit in capricorn.webp</a></td><td align="right">2020-12-16 16:18 </td><td align="right"> 30K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="37_37_Mercury%20in%20aries.webp">37_37_Mercury in aries.webp</a></td><td align="right">2021-09-09 09:45 </td><td align="right"> 15K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="37_Mercury%20in%20aries.webp">37_Mercury in aries.webp</a></td><td align="right">2020-12-16 16:19 </td><td align="right"> 15K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="37_detail_37_detail_mercury%20transit%20in%20aries.webp">37_detail_37_detail_mercury transit in aries.webp</a></td><td align="right">2021-09-09 09:45 </td><td align="right"> 31K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="37_detail_mercury%20transit%20in%20aries.webp">37_detail_mercury transit in aries.webp</a></td><td align="right">2020-12-16 16:19 </td><td align="right"> 31K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="38_38_Mercury%20in%20libra.webp">38_38_Mercury in libra.webp</a></td><td align="right">2021-09-22 17:40 </td><td align="right"> 15K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="38_Mercury%20in%20libra.webp">38_Mercury in libra.webp</a></td><td align="right">2020-12-14 16:22 </td><td align="right"> 15K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="38_detail_%E0%A4%AC%E0%A5%81%E0%A4%A7%20%E0%A4%97%E0%A5%8D%E0%A4%B0%E0%A4%B9%20%E0%A4%95%E0%A4%BE%20%E0%A4%A4%E0%A5%81%E0%A4%B2%E0%A4%BE%20%E0%A4%B0%E0%A4%BE%E0%A4%B6%E0%A4%BF%20%E0%A4%AE%E0%A5%87%E0%A4%82%20%E0%A4%97%E0%A5%8B%E0%A4%9A%E0%A4%B0.webp">38_detail_बुध ग्रह का तुला राशि में गोचर.webp</a></td><td align="right">2021-09-22 17:40 </td><td align="right"> 30K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="38_detail_mercury%20transit%20in%20libra.webp">38_detail_mercury transit in libra.webp</a></td><td align="right">2020-12-14 16:22 </td><td align="right"> 30K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="39_39_Mercury%20in%20leo.webp">39_39_Mercury in leo.webp</a></td><td align="right">2021-09-18 12:27 </td><td align="right"> 15K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="39_Mercury%20in%20leo.webp">39_Mercury in leo.webp</a></td><td align="right">2020-12-15 17:53 </td><td align="right"> 15K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="39_detail_39_detail_mercury%20transit%20in%20leo.webp">39_detail_39_detail_mercury transit in leo.webp</a></td><td align="right">2021-09-18 12:27 </td><td align="right"> 30K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="39_detail_mercury%20transit%20in%20leo.webp">39_detail_mercury transit in leo.webp</a></td><td align="right">2020-12-15 17:53 </td><td align="right"> 30K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="40_40_saturn%20in%20capricorn.webp">40_40_saturn in capricorn.webp</a></td><td align="right">2022-04-11 10:02 </td><td align="right"> 12K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="40_detail_40_detail_saturn%20transit%20in%20capricorn.webp">40_detail_40_detail_saturn transit in capricorn.webp</a></td><td align="right">2022-04-11 10:02 </td><td align="right"> 33K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="40_detail_saturn%20transit%20in%20capricorn.webp">40_detail_saturn transit in capricorn.webp</a></td><td align="right">2020-12-16 18:06 </td><td align="right"> 33K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="40_saturn%20in%20capricorn.webp">40_saturn in capricorn.webp</a></td><td align="right">2020-12-16 18:06 </td><td align="right"> 12K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="41_41_mercury%20in%20scorpio.webp">41_41_mercury in scorpio.webp</a></td><td align="right">2021-09-25 17:27 </td><td align="right"> 13K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="41_detail_41_detail_mercury%20in%20scorpio.webp">41_detail_41_detail_mercury in scorpio.webp</a></td><td align="right">2021-09-25 17:27 </td><td align="right"> 29K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="41_detail_mercury%20in%20scorpio.webp">41_detail_mercury in scorpio.webp</a></td><td align="right">2020-11-27 16:34 </td><td align="right"> 29K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="41_mercury%20in%20scorpio.webp">41_mercury in scorpio.webp</a></td><td align="right">2020-11-27 17:09 </td><td align="right"> 13K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="42_42_Mercury%20in%20taurus.webp">42_42_Mercury in taurus.webp</a></td><td align="right">2021-09-15 15:04 </td><td align="right"> 15K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="42_Mercury%20in%20taurus.webp">42_Mercury in taurus.webp</a></td><td align="right">2020-12-15 18:18 </td><td align="right"> 15K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="42_detail_42_detail_mercury%20transit%20in%20taurus.webp">42_detail_42_detail_mercury transit in taurus.webp</a></td><td align="right">2021-09-15 15:04 </td><td align="right"> 31K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="42_detail_mercury%20transit%20in%20taurus.webp">42_detail_mercury transit in taurus.webp</a></td><td align="right">2020-12-15 18:18 </td><td align="right"> 31K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="43_43_rahu%20in%20aries.webp">43_43_rahu in aries.webp</a></td><td align="right">2022-02-21 12:00 </td><td align="right"> 14K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="43_detail_43_detail_rahu%20transit%20in%20aries.webp">43_detail_43_detail_rahu transit in aries.webp</a></td><td align="right">2022-02-21 12:00 </td><td align="right"> 33K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="43_detail_rahu%20transit%20in%20aries.webp">43_detail_rahu transit in aries.webp</a></td><td align="right">2021-01-05 12:09 </td><td align="right"> 33K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="43_rahu%20in%20aries.webp">43_rahu in aries.webp</a></td><td align="right">2021-01-05 12:09 </td><td align="right"> 14K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="44_44_Mercury%20in%20Sagittarius.webp">44_44_Mercury in Sagittarius.webp</a></td><td align="right">2021-09-28 15:47 </td><td align="right"> 15K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="44_Mercury%20in%20Sagittarius.webp">44_Mercury in Sagittarius.webp</a></td><td align="right">2020-12-14 16:16 </td><td align="right"> 15K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="44_detail_44_detail_mercury%20transit%20in%20sagittarius.webp">44_detail_44_detail_mercury transit in sagittarius.webp</a></td><td align="right">2021-09-28 15:47 </td><td align="right"> 27K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="44_detail_mercury%20transit%20in%20sagittarius.webp">44_detail_mercury transit in sagittarius.webp</a></td><td align="right">2020-12-14 16:13 </td><td align="right"> 27K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="45_45_Mercury%20in%20virgo.webp">45_45_Mercury in virgo.webp</a></td><td align="right">2021-09-21 12:04 </td><td align="right"> 15K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="45_Mercury%20in%20virgo.webp">45_Mercury in virgo.webp</a></td><td align="right">2020-12-15 17:52 </td><td align="right"> 15K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="45_detail_45_detail_mercury%20transit%20in%20virgo.webp">45_detail_45_detail_mercury transit in virgo.webp</a></td><td align="right">2021-09-21 12:04 </td><td align="right"> 31K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="45_detail_mercury%20transit%20in%20virgo.webp">45_detail_mercury transit in virgo.webp</a></td><td align="right">2020-12-15 17:52 </td><td align="right"> 31K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="46_detail_rahu%20transit%20in%20taurus.webp">46_detail_rahu transit in taurus.webp</a></td><td align="right">2022-07-11 11:36 </td><td align="right"> 30K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="46_rahu%20in%20taurus.webp">46_rahu in taurus.webp</a></td><td align="right">2022-07-11 11:35 </td><td align="right"> 15K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="47_47_Mercury%20in%20pisces.webp">47_47_Mercury in pisces.webp</a></td><td align="right">2021-10-15 16:05 </td><td align="right"> 16K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="47_Mercury%20in%20pisces.webp">47_Mercury in pisces.webp</a></td><td align="right">2020-12-16 16:20 </td><td align="right"> 16K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="47_detail_47_detail_mercury%20transit%20in%20pisces.webp">47_detail_47_detail_mercury transit in pisces.webp</a></td><td align="right">2021-10-15 16:05 </td><td align="right"> 31K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="47_detail_mercury%20transit%20in%20pisces.webp">47_detail_mercury transit in pisces.webp</a></td><td align="right">2020-12-16 16:20 </td><td align="right"> 31K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="53_detail_rahu%20transit%20in%20Sagittarius.webp">53_detail_rahu transit in Sagittarius.webp</a></td><td align="right">2022-07-11 10:51 </td><td align="right"> 34K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="53_rahu%20in%20Sagittarius.webp">53_rahu in Sagittarius.webp</a></td><td align="right">2022-07-11 10:51 </td><td align="right"> 15K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="54_detail_rahu%20in%20Aquarius.webp">54_detail_rahu in Aquarius.webp</a></td><td align="right">2022-07-07 10:52 </td><td align="right"> 16K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="54_detail_rahu%20transit%20in%20capricorn.webp">54_detail_rahu transit in capricorn.webp</a></td><td align="right">2021-01-05 12:21 </td><td align="right"> 36K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="54_rahu%20in%20Aquarius.webp">54_rahu in Aquarius.webp</a></td><td align="right">2022-07-07 10:51 </td><td align="right"> 16K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="55_detail_rahu%20transit%20in%20Aquarius.webp">55_detail_rahu transit in Aquarius.webp</a></td><td align="right">2021-01-05 12:16 </td><td align="right"> 35K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="55_rahu%20in%20Aquarius.webp">55_rahu in Aquarius.webp</a></td><td align="right">2021-01-05 12:16 </td><td align="right"> 16K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="56_detail_rahu%20transit%20in%20pisces.webp">56_detail_rahu transit in pisces.webp</a></td><td align="right">2021-01-05 12:15 </td><td align="right"> 36K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="56_rahu%20in%20pisces.webp">56_rahu in pisces.webp</a></td><td align="right">2021-01-05 12:15 </td><td align="right"> 16K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="58_58_jupiter%20in%20pisces.webp">58_58_jupiter in pisces.webp</a></td><td align="right">2022-04-09 15:17 </td><td align="right"> 15K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="58_detail_58_detail_Jupiter%20transit%20in%20pisces.webp">58_detail_58_detail_Jupiter transit in pisces.webp</a></td><td align="right">2022-04-09 15:17 </td><td align="right"> 32K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="58_detail_Jupiter%20transit%20in%20pisces.webp">58_detail_Jupiter transit in pisces.webp</a></td><td align="right">2020-12-19 17:36 </td><td align="right"> 32K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="58_jupiter%20in%20pisces.webp">58_jupiter in pisces.webp</a></td><td align="right">2020-12-19 17:36 </td><td align="right"> 15K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="59_59_Mars%20in%20virgo.webp">59_59_Mars in virgo.webp</a></td><td align="right">2021-07-23 17:23 </td><td align="right"> 14K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="59_Mars%20in%20virgo.webp">59_Mars in virgo.webp</a></td><td align="right">2020-12-19 16:26 </td><td align="right"> 14K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="59_detail_59_detail_mars%20transit%20in%20virgo.webp">59_detail_59_detail_mars transit in virgo.webp</a></td><td align="right">2021-07-23 17:23 </td><td align="right"> 30K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="59_detail_mars%20transit%20in%20virgo.webp">59_detail_mars transit in virgo.webp</a></td><td align="right">2020-12-19 16:26 </td><td align="right"> 30K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="60_60_jupiter%20in%20aries.webp">60_60_jupiter in aries.webp</a></td><td align="right">2021-09-18 12:42 </td><td align="right"> 14K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="60_detail_60_detail_Jupiter%20transit%20in%20aries.webp">60_detail_60_detail_Jupiter transit in aries.webp</a></td><td align="right">2021-09-18 12:42 </td><td align="right"> 32K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="60_detail_Jupiter%20transit%20in%20aries.webp">60_detail_Jupiter transit in aries.webp</a></td><td align="right">2020-12-19 17:36 </td><td align="right"> 32K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="60_jupiter%20in%20aries.webp">60_jupiter in aries.webp</a></td><td align="right">2020-12-19 17:36 </td><td align="right"> 14K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="61_61_jupiter%20in%20taurus.webp">61_61_jupiter in taurus.webp</a></td><td align="right">2022-06-21 17:50 </td><td align="right"> 14K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="61_detail_61_jupiter%20in%20taurus.webp">61_detail_61_jupiter in taurus.webp</a></td><td align="right">2022-06-21 17:50 </td><td align="right"> 14K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="61_detail_Jupiter%20transit%20in%20taurus.webp">61_detail_Jupiter transit in taurus.webp</a></td><td align="right">2020-12-19 17:37 </td><td align="right"> 32K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="61_jupiter%20in%20taurus.webp">61_jupiter in taurus.webp</a></td><td align="right">2020-12-19 17:37 </td><td align="right"> 14K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="62_62_jupiter%20in%20virgo.webp">62_62_jupiter in virgo.webp</a></td><td align="right">2022-06-29 12:39 </td><td align="right"> 13K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="62_detail_62_detail_Jupiter%20transit%20in%20virgo.webp">62_detail_62_detail_Jupiter transit in virgo.webp</a></td><td align="right">2022-06-29 12:39 </td><td align="right"> 31K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="62_detail_Jupiter%20transit%20in%20virgo.webp">62_detail_Jupiter transit in virgo.webp</a></td><td align="right">2020-12-19 17:52 </td><td align="right"> 31K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="62_jupiter%20in%20virgo.webp">62_jupiter in virgo.webp</a></td><td align="right">2020-12-19 17:52 </td><td align="right"> 13K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="63_detail_Jupiter%20transit%20in%20scorpio.webp">63_detail_Jupiter transit in scorpio.webp</a></td><td align="right">2022-07-13 12:07 </td><td align="right"> 31K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="63_jupiter%20in%20scorpio.webp">63_jupiter in scorpio.webp</a></td><td align="right">2022-07-13 12:07 </td><td align="right"> 15K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="64_detail_Jupiter%20transit%20in%20libra.webp">64_detail_Jupiter transit in libra.webp</a></td><td align="right">2022-07-11 13:09 </td><td align="right"> 32K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="64_jupiter%20in%20libra.webp">64_jupiter in libra.webp</a></td><td align="right">2022-07-11 13:09 </td><td align="right"> 14K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="65_65_jupiter%20in%20leo.webp">65_65_jupiter in leo.webp</a></td><td align="right">2022-06-25 17:51 </td><td align="right"> 14K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="65_detail_65_detail_Jupiter%20transit%20in%20leo.webp">65_detail_65_detail_Jupiter transit in leo.webp</a></td><td align="right">2022-06-25 17:51 </td><td align="right"> 30K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="65_detail_Jupiter%20transit%20in%20leo.webp">65_detail_Jupiter transit in leo.webp</a></td><td align="right">2020-12-19 17:54 </td><td align="right"> 30K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="65_jupiter%20in%20leo.webp">65_jupiter in leo.webp</a></td><td align="right">2020-12-19 17:54 </td><td align="right"> 14K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="66_66_jupiter%20in%20gemini.webp">66_66_jupiter in gemini.webp</a></td><td align="right">2022-04-30 13:31 </td><td align="right"> 13K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="66_detail_66_detail_Jupiter%20transit%20in%20gemini.webp">66_detail_66_detail_Jupiter transit in gemini.webp</a></td><td align="right">2022-04-30 13:31 </td><td align="right"> 32K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="66_detail_Jupiter%20transit%20in%20gemini.webp">66_detail_Jupiter transit in gemini.webp</a></td><td align="right">2020-12-19 18:00 </td><td align="right"> 32K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="66_jupiter%20in%20gemini.webp">66_jupiter in gemini.webp</a></td><td align="right">2020-12-19 18:00 </td><td align="right"> 13K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="67_67_jupiter%20in%20cancer.webp">67_67_jupiter in cancer.webp</a></td><td align="right">2022-06-29 12:46 </td><td align="right"> 13K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="67_detail_67_detail_Jupiter%20transit%20in%20cancer.webp">67_detail_67_detail_Jupiter transit in cancer.webp</a></td><td align="right">2022-06-29 12:46 </td><td align="right"> 32K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="67_detail_Jupiter%20transit%20in%20cancer.webp">67_detail_Jupiter transit in cancer.webp</a></td><td align="right">2020-12-19 18:00 </td><td align="right"> 32K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="67_jupiter%20in%20cancer.webp">67_jupiter in cancer.webp</a></td><td align="right">2020-12-19 18:00 </td><td align="right"> 13K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="68_68_saturn%20in%20aries.webp">68_68_saturn in aries.webp</a></td><td align="right">2022-09-24 14:58 </td><td align="right">7.1K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="68_detail_68_detail_saturn%20transit%20in%20aries.webp">68_detail_68_detail_saturn transit in aries.webp</a></td><td align="right">2022-09-24 14:58 </td><td align="right"> 19K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="68_detail_saturn%20transit%20in%20aries.webp">68_detail_saturn transit in aries.webp</a></td><td align="right">2021-01-05 11:54 </td><td align="right"> 19K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="68_saturn%20in%20aries.webp">68_saturn in aries.webp</a></td><td align="right">2021-01-05 11:54 </td><td align="right">7.1K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="72_72_saturn%20in%20Aquarius.webp">72_72_saturn in Aquarius.webp</a></td><td align="right">2022-04-11 10:01 </td><td align="right">8.2K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="72_detail_72_detail_saturn%20transit%20in%20Aquarius.webp">72_detail_72_detail_saturn transit in Aquarius.webp</a></td><td align="right">2022-04-11 10:01 </td><td align="right"> 21K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="72_detail_saturn%20transit%20in%20Aquarius.webp">72_detail_saturn transit in Aquarius.webp</a></td><td align="right">2021-01-05 11:34 </td><td align="right"> 21K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="72_saturn%20in%20Aquarius.webp">72_saturn in Aquarius.webp</a></td><td align="right">2021-01-05 11:47 </td><td align="right">8.2K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="73_73_saturn%20in%20pisces.webp">73_73_saturn in pisces.webp</a></td><td align="right">2022-11-09 13:25 </td><td align="right">8.3K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="73_detail_73_detail_saturn%20transit%20in%20pisces.webp">73_detail_73_detail_saturn transit in pisces.webp</a></td><td align="right">2022-11-09 13:25 </td><td align="right"> 21K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="73_detail_saturn%20transit%20in%20pisces.webp">73_detail_saturn transit in pisces.webp</a></td><td align="right">2021-01-05 11:50 </td><td align="right"> 21K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="73_saturn%20in%20pisces.webp">73_saturn in pisces.webp</a></td><td align="right">2021-01-05 11:50 </td><td align="right">8.3K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="74_chandra%20grahan.webp">74_chandra grahan.webp</a></td><td align="right">2020-11-26 17:32 </td><td align="right">4.1K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="74_detail_lunar%20eclipse.webp">74_detail_lunar eclipse.webp</a></td><td align="right">2020-11-26 17:36 </td><td align="right">9.7K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="75_75_Mars%20in%20Sagittarius.webp">75_75_Mars in Sagittarius.webp</a></td><td align="right">2021-08-27 13:40 </td><td align="right"> 14K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="75_Mars%20in%20Sagittarius.webp">75_Mars in Sagittarius.webp</a></td><td align="right">2020-12-19 16:32 </td><td align="right"> 14K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="75_detail_75_detail_Mars%20Transit%20in%20Sagittarius.webp">75_detail_75_detail_Mars Transit in Sagittarius.webp</a></td><td align="right">2021-08-27 13:40 </td><td align="right"> 32K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="75_detail_Mars%20Transit%20in%20Sagittarius.webp">75_detail_Mars Transit in Sagittarius.webp</a></td><td align="right">2020-12-19 16:32 </td><td align="right"> 32K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="79_79_Mars%20in%20scorpio.webp">79_79_Mars in scorpio.webp</a></td><td align="right">2021-09-07 17:01 </td><td align="right"> 13K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="79_Mars%20in%20scorpio.webp">79_Mars in scorpio.webp</a></td><td align="right">2020-12-19 16:27 </td><td align="right"> 13K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="79_detail_79_detail_mars%20transit%20in%20scorpio.webp">79_detail_79_detail_mars transit in scorpio.webp</a></td><td align="right">2021-09-07 17:01 </td><td align="right"> 33K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="79_detail_mars%20transit%20in%20scorpio.webp">79_detail_mars transit in scorpio.webp</a></td><td align="right">2020-12-19 16:27 </td><td align="right"> 33K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="80_80_saturn%20in%20taurus.webp">80_80_saturn in taurus.webp</a></td><td align="right">2022-04-11 10:00 </td><td align="right">7.2K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="80_detail_80_detail_saturn%20transit%20in%20taurus.webp">80_detail_80_detail_saturn transit in taurus.webp</a></td><td align="right">2022-04-11 10:00 </td><td align="right"> 20K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="80_detail_saturn%20transit%20in%20taurus.webp">80_detail_saturn transit in taurus.webp</a></td><td align="right">2021-01-05 11:55 </td><td align="right"> 20K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="80_saturn%20in%20taurus.webp">80_saturn in taurus.webp</a></td><td align="right">2021-01-05 11:55 </td><td align="right">7.2K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="82_82_Mars%20in%20taurus.webp">82_82_Mars in taurus.webp</a></td><td align="right">2021-07-26 11:49 </td><td align="right"> 14K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="82_Mars%20in%20taurus.webp">82_Mars in taurus.webp</a></td><td align="right">2020-12-19 16:28 </td><td align="right"> 14K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="82_detail_82_detail_mars%20transit%20in%20taurus.webp">82_detail_82_detail_mars transit in taurus.webp</a></td><td align="right">2021-07-26 11:49 </td><td align="right"> 31K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="82_detail_mars%20transit%20in%20taurus.webp">82_detail_mars transit in taurus.webp</a></td><td align="right">2020-12-19 16:28 </td><td align="right"> 31K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="84_84_Mars%20in%20libra.webp">84_84_Mars in libra.webp</a></td><td align="right">2021-07-23 17:40 </td><td align="right"> 14K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="84_Mars%20in%20libra.webp">84_Mars in libra.webp</a></td><td align="right">2020-12-19 16:28 </td><td align="right"> 14K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="84_detail_84_detail_mars%20transit%20in%20libra.webp">84_detail_84_detail_mars transit in libra.webp</a></td><td align="right">2021-07-23 17:40 </td><td align="right"> 32K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="84_detail_mars%20transit%20in%20libra.webp">84_detail_mars transit in libra.webp</a></td><td align="right">2020-12-19 16:28 </td><td align="right"> 32K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="85_85_Mars%20in%20pisces.webp">85_85_Mars in pisces.webp</a></td><td align="right">2021-09-01 17:53 </td><td align="right"> 15K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="85_Mars%20in%20pisces.webp">85_Mars in pisces.webp</a></td><td align="right">2020-12-14 18:23 </td><td align="right"> 15K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="85_detail_85_detail_mars%20transit%20in%20pisces.webp">85_detail_85_detail_mars transit in pisces.webp</a></td><td align="right">2021-09-01 17:53 </td><td align="right"> 31K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="85_detail_mars%20transit%20in%20pisces.webp">85_detail_mars transit in pisces.webp</a></td><td align="right">2020-12-14 18:23 </td><td align="right"> 31K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="93_detail_Jupiter%20transit%20in%20Sagittarius.webp">93_detail_Jupiter transit in Sagittarius.webp</a></td><td align="right">2022-07-07 13:17 </td><td align="right"> 32K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="93_jupiter%20in%20Sagittarius.webp">93_jupiter in Sagittarius.webp</a></td><td align="right">2022-07-07 13:17 </td><td align="right"> 15K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="95_95_jupiter%20in%20Aquarius.webp">95_95_jupiter in Aquarius.webp</a></td><td align="right">2022-07-23 16:44 </td><td align="right"> 15K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="95_detail_95_detail_Jupiter%20transit%20in%20Aquarius.webp">95_detail_95_detail_Jupiter transit in Aquarius.webp</a></td><td align="right">2022-07-23 16:44 </td><td align="right"> 32K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="95_detail_Jupiter%20transit%20in%20Aquarius.webp">95_detail_Jupiter transit in Aquarius.webp</a></td><td align="right">2020-12-19 18:08 </td><td align="right"> 32K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="95_jupiter%20in%20Aquarius.webp">95_jupiter in Aquarius.webp</a></td><td align="right">2020-12-19 18:08 </td><td align="right"> 15K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/image2.gif" alt="[IMG]"></td><td><a href="96_detail_ketu-transit%20in%20libra.jpg">96_detail_ketu-transit in libra.jpg</a></td><td align="right">2022-02-12 11:58 </td><td align="right"> 26K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/image2.gif" alt="[IMG]"></td><td><a href="96_detail_ketu%20transit%20in%20virgo.jpg">96_detail_ketu transit in virgo.jpg</a></td><td align="right">2022-02-12 11:40 </td><td align="right"> 26K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/image2.gif" alt="[IMG]"></td><td><a href="96_ketu-transit%20in%20libra.jpg">96_ketu-transit in libra.jpg</a></td><td align="right">2022-02-12 11:58 </td><td align="right"> 26K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/image2.gif" alt="[IMG]"></td><td><a href="96_ketu%20transit%20in%20virgo.jpg">96_ketu transit in virgo.jpg</a></td><td align="right">2022-02-12 11:40 </td><td align="right"> 26K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/image2.gif" alt="[IMG]"></td><td><a href="99_OIP.jpg">99_OIP.jpg</a></td><td align="right">2021-11-02 18:28 </td><td align="right"> 16K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="100_100_jupiter%20saturn.webp">100_100_jupiter saturn.webp</a></td><td align="right">2021-10-29 13:31 </td><td align="right"> 10K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="100_detail_100_detail_jupiter%20saturn%20conjuction.webp">100_detail_100_detail_jupiter saturn conjuction.webp</a></td><td align="right">2021-10-29 13:31 </td><td align="right"> 30K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="100_detail_jupiter%20saturn%20conjuction.webp">100_detail_jupiter saturn conjuction.webp</a></td><td align="right">2020-12-17 18:31 </td><td align="right"> 30K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/unknown.gif" alt="[   ]"></td><td><a href="100_jupiter%20saturn.webp">100_jupiter saturn.webp</a></td><td align="right">2020-12-17 18:31 </td><td align="right"> 10K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/image2.gif" alt="[IMG]"></td><td><a href="101_detail_saturn%20transit%20in%20cancer.jpg">101_detail_saturn transit in cancer.jpg</a></td><td align="right">2022-02-12 11:22 </td><td align="right"> 28K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/image2.gif" alt="[IMG]"></td><td><a href="101_saturn%20transit%20in%20cancer.jpg">101_saturn transit in cancer.jpg</a></td><td align="right">2022-02-12 11:36 </td><td align="right"> 28K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/image2.gif" alt="[IMG]"></td><td><a href="102_detail_ketu%20transit%20in%20virgo.jpg">102_detail_ketu transit in virgo.jpg</a></td><td align="right">2022-02-12 11:39 </td><td align="right"> 26K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/image2.gif" alt="[IMG]"></td><td><a href="102_ketu%20transit%20in%20virgo.jpg">102_ketu transit in virgo.jpg</a></td><td align="right">2022-02-12 11:39 </td><td align="right"> 26K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="../../icons/image2.gif" alt="[IMG]"></td><td><a href="102_saturn%20transit%20in%20cancer.jpg">102_saturn transit in cancer.jpg</a></td><td align="right">2022-02-12 11:36 </td><td align="right"> 28K</td><td>&nbsp;</td></tr>
<tr><th colspan="5"><hr></th></tr>
</table>
<address>Apache/2.4.41 (Ubuntu) Server at www.vinaybajrangi.com Port 443</address>
</body></html>
