export default function UpcomingVisits() {
    return (
        <div className="container mx-auto">
            <div className="font-bold text-2xl text-center gap-x-6 bg-orange-600 px-6 py-2.5 sm:px-3.5 sm:before:flex-1">
                <h1 className="justify-center leading-6 text-white">Dr. Vinay Bajrangi explains the importance of horoscope</h1>
            </div>
            <div className="text-sm font-semibold p-8 text-justify text-gray-800 leading-8">

                <p><span><span >Hello Mumbai! Soon, Dr. Vinay Bajrangi will visit Mumbai, and you have the golden opportunity to get Astrological guidance from him directly in your city.</span></span></p>
                <p><em>“An astrologer serves as a lighthouse in difficult times of life”</em></p>
                <p><span><span >Mumbai People, your quest to meet the best astrologer in your own town ends here! The </span><a className="text-blue-700" href="https://www.vinaybajrangi.com/" ><span ><strong>Best Astrologer in India</strong></span></a><span >, Dr. Vinay Bajrangi, will soon be in Mumbai. Schedule your appointments to solve unsolved mysteries of your life now!</span></span></p>
                
                <p><span><span >Astrology is an ancient wisdom of studying celestial movements in the sky and analyzing their effects on the mankind. You will be amazed to know that even tiniest of movement in the sky can bring significant changes in your life. If these planetary movements can be figured out correctly, all of our problems in life can be controlled effectively.&nbsp;</span></span></p>
                
                <p><span><span >But at the same time, the astrologer has to be experienced and knowledgeable enough to exactly decode the planetary language. Dr. Vinay Bajrangi is on such astrologer who is known for his vast knowledge and 100% accurate predictions. With a never ending list of satisfied clients, you can’t go wrong with his astrological advice ever in your life. He may guide you through any tough phase related to any area of life. So, visit him to get effective solutions to the problems giving you sleepless nights!</span></span></p>
                <h2 className="py-4 justify-center text-lg leading-6 text-black/1">
                    <span><strong>Dr. Vinay Bajrangi- A well-known name in the Astrology world</strong></span></h2>
                <p><span><span >Dr. Vinay Bajrangi is a familiar name to those interested in Astrology. The face you generally see on the cover pages of famous magazines will just become a reality for Mumbai people. Known for his most accurate predictions and most effective remedial measures, Dr. Vinay Bajrangi offers directions for exploring and acquiring solutions to the deepest queries of life. Get the </span><a className="text-blue-700" href="https://www.vinaybajrangi.com/career-astrology/right-career-selection.php" ><span ><strong>Best Career Astrological Guidance</strong></span></a><span > and suggestions from him related to your moon sign, zodiac sign, planets, nakshatras, various astrological houses etc. in the simplest way.&nbsp;</span></span></p>
                
                <p><span><span >He is a celebrity astrologer with end number of satisfied clients across the globe. Get advice from the</span><strong> Best Astrologer in the country</strong><span >, who will deeply study and analyze your kundli to show you the most suitable path with in-depth astrology reports. The astrology reports may give valuable insights about different aspects of life like education, marriage, career, health, divorce, foreign settlement, business or job etc.&nbsp;&nbsp;&nbsp;</span></span></p>
                
                <p><span><span >The clients or visitors may harness the benefits of planetary transitions with his timely suggestions and advice. One also learns as to how to stand brave while sailing smoothly through difficult times in life. Get valuable information to understand the sudden happenings in life as caused by retrogression of planets. Dr. Vinay Bajrangi is a famous name to get expert and most genuine astrology consultation. Whenever, there is doubt in your mind and you wish to understand what’s happening around, just visit him to decode planetary positions and get solutions against your troubles in life.&nbsp;</span></span></p>
                
                <p><span><span >He is an experienced and celebrated</span><strong> Best Vedic astrologer </strong><span >who specializes in rectifying planets through most amazing yet uncommon ways. His main expertise lies in </span><a className="text-blue-700" href="https://www.vinaybajrangi.com/life-predictions/karma-correction.php" ><span ><strong>Karma Rectification</strong></span></a><span >. He believes that if one behaves as per the requirements of the planets, there is no chance of failure in life. But that requires very deep analysis of the kundli which can be done by the best astrologers like him only. So, most of his remedies revolve around improving your habits and life style along with other astrological measures.</span></span></p>
                
                <p><span><span >Get reliable astrology solutions for all your married problems. Today we see many people facing issues in their married life. </span><a className="text-blue-700" href="https://www.vinaybajrangi.com/marriage-astrology.php" ><span ><strong>Marriage Astrology</strong></span></a><span > helps to detect the reason behind these problems, may be some bad planetary effects are ruining your married life. Know the true application of </span><a className="text-blue-700" href="https://www.vinaybajrangi.com/marriage-astrology/kundli-matching-horoscopes-matching-for-marriage.php" ><span ><strong>Kundli Milan</strong></span></a><span > procedure which is rather a deep process than it seems. Married couples may consult him to understand what is the real cause behind problem in their married life? He has helped many to save their falling relations with correct guidance. Some temporary bad transits may cause a permanent damage to a relation, save it before it’s too late!&nbsp;&nbsp;</span></span></p>
                
                <p><span><span >Seek </span><a className="text-blue-700" href="https://www.vinaybajrangi.com/marriage-astrology/marriage-life-problems-reasons.php" ><span ><strong>Solution for Marriage issues by astrology</strong></span></a><span > and see things turning positive before your eyes. You just can’t help but wondering at his meticulous astrological predictions matching perfectly to the timeline in your life. Why you are facing </span><a className="text-blue-700" href="https://www.vinaybajrangi.com/marriage-astrology/delay-in-marriage-reasons-solutions.php" ><span ><strong>Delay in Marriage</strong></span></a><span >? Or why your marriage is not running smooth? Or why you face indifferences in thoughts with your life partner can be determined correctly with a visit to him. He is an expert in solving marriage issues and saved many marriages at the verge of breaking. It’s not about saving a marriage at all costs but to get the correct guidance whether one should go forward in a marriage or come out of it. He provides </span><strong>pre-marriage counseling</strong><span > and </span><strong>post-marriage counseling</strong><span > to help the couple know the peculiarities of a marriage.&nbsp;&nbsp;&nbsp;&nbsp;</span></span></p>
                
                <p><span><span >If you are facing problems in your career then he is the right person to consult with. You may know the possible reasons behind failure or lack of interest in your work field through accurate </span><a className="text-blue-700" href="https://www.vinaybajrangi.com/career-astrology.php" ><span ><strong>Career Prediction</strong></span></a><span > made by him. Consult him to know whether you are in the career field best suited to you. His deep knowledge and correct diagnosis makes it easier to know whether business or job will suit you more. </span><a className="text-blue-700" href="https://www.vinaybajrangi.com/career-astrology/job-or-business.php" ><span ><strong>Job or Business Prediction</strong></span></a><strong> </strong><span >is the best way to tap your resources to the fullest. Sometimes we adapt a career not meant for us, so, visit him and know your possibilities!&nbsp;</span></span></p>
                
                <p><span><span >All kinds of problems addressed in business or profession can be effectively tackled with an astrological guidance. </span><a className="text-blue-700" href="https://www.vinaybajrangi.com/business-astrology.php" ><span ><strong>Business Astrology</strong></span></a><span > identifies your prospects in business and provides effective ways to improve your business in no time. The planetary yoga in your kundli may ascertain your quantum of wealth and resources to earn them. When you know, from where the wealth is expected to come into your life, you tend to put your efforts in the right directions. He may tell you the ways how to get rich and wealthy in life? Know your </span><strong>Wealth Horoscope</strong><span > with the best Astrologer in your town!</span></span></p>
                
                <p><span><span >Dr. Vinay Bajrangi has helped millions of people through perfect astrological guidance and has showed them the brightest path in life. He has an experience of more than three decades in the astrology field. The excellent intuitive skills, he holds and in depth </span><a className="text-blue-700" href="https://www.vinaybajrangi.com/kundli.php" ><span ><strong>Kundli Analysis</strong></span></a><span > helps to solve even the hardest of the problems in life in no time.&nbsp;</span></span></p>
                
                <p><span><span >Don’t let your child waste his time and resources in the education stream not suitable for him. The reason behind the falling grades, lack of interest and poor performance of your child in academics can be linked to negative planetary effects. Remove these bad effects of planets with effective remedies and guidance. Visit him if you wish to know </span><strong>how to choose the right steam of education</strong><span > for your child? Get the </span><strong>education horoscope</strong><span > and know the possibilities of your child in future. Good education today will affirm a good career tomorrow!&nbsp;</span></span></p>
                
                <p><span><span >If you are keen to know what your </span><a className="text-blue-700" href="https://www.vinaybajrangi.com/health-astrology.php" ><span ><strong>Health Horoscope</strong></span></a><strong> </strong><span >holds for you, you can consult him to get the most genuine astrological guidance. The possibilities of getting suffered from complex diseases or the chances to recover from a deadly disease can be accurately determined with an astrology consultation. There are many people who have turn victorious out of the complex diseases after following his advice. Take precautions for your health in advance to avoid regrets later. He may tell you the time period of falling ill and if you follow the remedies as suggested by him during that time, you may beat those diseases which your medical reports have just announced for you! Get your </span><a className="text-blue-700" href="https://www.vinaybajrangi.com/horoscope/daily-horoscope.php" ><span ><strong>Health Horoscope Today</strong></span></a><span >!</span></span></p>
                
                <p><span><span >With his profound knowledge of every segment of the astrology world, he is the best astrologer in India. The dosha in our kundli trouble us a lot and leave us stranded without us realizing the reason. Nothing seems to fall in place and we face failures in all directions. Your kundli may contain inauspicious dosha which might be the prime reason for troubles in life.&nbsp;</span></span></p>
                
                <p><span><span >Rectify the ill effects of planetary combinations or </span><a href="https://www.vinaybajrangi.com/kundli-doshas.php" ><span ><strong>Kundli Dosha</strong></span></a><strong> </strong><span >with the correct astrological remedies as suggested by him. He firmly believes in karma rectification and guides his clients through performing karma modifications in their lives rather than following remedies mindlessly. His logical and enlightening analysis will leave you mesmerized with the charm of Astrology. Understand the importance of astrology in its true sense which has been ruined by those making money in the name of astrology. Astrology is the way of life and you will realize this fact after meeting him. Visit Dr. Vinay Bajrangi to attract health, luck, success and prosperity in life!</span></span></p>

            </div>
        </div>
    )
}





